CREATE TABLE blogs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    blog TEXT NOT NULL,
    banned TINYINT(1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;;